---
- hosts: all
  become: yes
  tasks:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present
    - name: update
      apt:
        update_cache: yes
    - name: install server apps
      apt:
        name:
          - nodejs
          - python3
          - g++
          - make
          - npm
          - python3-pip
          - apt-transport-https
          - docker
        state: latest
    - name: add zyzyx to docker group
      user:
        name: "zyzyx"
        groups: docker
        append: yes
    - name: install dockly
      shell: npm install -g dockly
