---
- hosts: all
  become: yes
  tasks:
    - name: update
      apt:
        update_cache: yes
    - name: install server apps
      apt:
        name:
          - nodejs
          - python3
          - g++
          - make
          - npm
          - python3-pip
          - apt-transport-https
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
    - name: add zyzyx to docker group
      user:
        name: "zyzyx"
        groups: docker
        append: yes
    - name: install dockly
      shell: npm install -g dockly
